### PR TITLE
WIP: Bootstrap basic cache

### LINKED ISSUE #62: Cache repositories
the idea is to cache locally the plugins and groups

### PR DESCRIPTION
**Pull request by harsimranmaan**
Closes #62

### CODE REVIEW

**Comment by alfsuse** [comment]
@harsimranmaan checked on windows and it works like charm. Great stuff!

First time I hit the ```k3ai-cli list```
I hade the following:
```BASH
PS C:\Users\AlessandroFesta\Documents\k3ai-core-cache> .\bin\k3ai-cli.exe list
C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core
<nil>
C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\argo-workflow
open C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\argo-workflow\plugin.yaml: The system cannot find the path specified.
C:\Users\AlessandroFesta\.k3ai\cache\kf5i\k3ai-plugins\main\core\plugins\argo-workflow
<nil>
C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\ci-tests
open C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\ci-tests\plugin.yaml: The system cannot find the path specified.
C:\Users\AlessandroFesta\.k3ai\cache\kf5i\k3ai-plugins\main\core\plugins\ci-tests
<nil>
C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\h2o-single
open C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\h2o-single\plugin.yaml: The system cannot find the path specified.
C:\Users\AlessandroFesta\.k3ai\cache\kf5i\k3ai-plugins\main\core\plugins\h2o-single
<nil>
C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\jupyter-minimal
open C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\jupyter-minimal\plugin.yaml: The system cannot find the path specified.
C:\Users\AlessandroFesta\.k3ai\cache\kf5i\k3ai-plugins\main\core\plugins\jupyter-minimal
<nil>
C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\katib
open C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\katib\plugin.yaml: The system cannot find the path specified.
C:\Users\AlessandroFesta\.k3ai\cache\kf5i\k3ai-plugins\main\core\plugins\katib
<nil>
C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\kf-pipelines-tekton
open C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\kf-pipelines-tekton\plugin.yaml: The system cannot find the path specified.
C:\Users\AlessandroFesta\.k3ai\cache\kf5i\k3ai-plugins\main\core\plugins\kf-pipelines-tekton
<nil>
C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\kubeflow-pipelines
open C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\kubeflow-pipelines\plugin.yaml: The system cannot find the path specified.
C:\Users\AlessandroFesta\.k3ai\cache\kf5i\k3ai-plugins\main\core\plugins\kubeflow-pipelines
<nil>
C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\mpi-op
open C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\mpi-op\plugin.yaml: The system cannot find the path specified.
C:\Users\AlessandroFesta\.k3ai\cache\kf5i\k3ai-plugins\main\core\plugins\mpi-op
<nil>
C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\pytorch-op
open C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\pytorch-op\plugin.yaml: The system cannot find the path specified.
C:\Users\AlessandroFesta\.k3ai\cache\kf5i\k3ai-plugins\main\core\plugins\pytorch-op
<nil>
C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\tekton
open C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\tekton\plugin.yaml: The system cannot find the path specified.
C:\Users\AlessandroFesta\.k3ai\cache\kf5i\k3ai-plugins\main\core\plugins\tekton
<nil>
C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\tensorflow-op
open C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\tensorflow-op\plugin.yaml: The system cannot find the path specified.
C:\Users\AlessandroFesta\.k3ai\cache\kf5i\k3ai-plugins\main\core\plugins\tensorflow-op
<nil>
Name                           Description
argo-workflow                  Argo Workflow plugin
ci-tests                       For CI Tests
h2o-single                     H2O.ai
jupyter-minimal                Minimal Jupyter Configuration
katib                          Kubeflow Katib
kf-pipelines-tekton            Kubeflow Pipelines based on Tekton
kubeflow-pipelines             Kubeflow Pipelines platform agnostic
mpi-op                         MPI-Operator
pytorch-op                     Pytorch op
tekton                         Kubeflow Pipelines based on Tekton
tensorflow-op                  Kubeflow Tensorflow
```

second time the result were
```BASH
PS C:\Users\AlessandroFesta\Documents\k3ai-core-cache> .\bin\k3ai-cli.exe list
cache hit
C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\argo-workflow
open C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\argo-workflow\plugin.yaml: The system cannot find the path specified.
cache hit
C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\ci-tests
open C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\ci-tests\plugin.yaml: The system cannot find the path specified.
cache hit
C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\h2o-single
open C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\h2o-single\plugin.yaml: The system cannot find the path specified.
cache hit
C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\jupyter-minimal
open C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\jupyter-minimal\plugin.yaml: The system cannot find the path specified.
cache hit
C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\katib
open C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\katib\plugin.yaml: The system cannot find the path specified.
cache hit
C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\kf-pipelines-tekton
open C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\kf-pipelines-tekton\plugin.yaml: The system cannot find the path specified.     
cache hit
C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\kubeflow-pipelines
open C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\kubeflow-pipelines\plugin.yaml: The system cannot find the path specified.      
cache hit
C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\mpi-op
open C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\mpi-op\plugin.yaml: The system cannot find the path specified.
cache hit
C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\pytorch-op
open C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\pytorch-op\plugin.yaml: The system cannot find the path specified.
cache hit
C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\tekton
open C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\tekton\plugin.yaml: The system cannot find the path specified.
cache hit
C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\tensorflow-op
open C:\Users\AlessandroFesta\.k3ai\cache\repos\kf5i\k3ai-plugins\contents\core\plugins\tensorflow-op\plugin.yaml: The system cannot find the path specified.
cache hit
Name                           Description
argo-workflow                  Argo Workflow plugin
ci-tests                       For CI Tests
h2o-single                     H2O.ai
jupyter-minimal                Minimal Jupyter Configuration
katib                          Kubeflow Katib
kf-pipelines-tekton            Kubeflow Pipelines based on Tekton
kubeflow-pipelines             Kubeflow Pipelines platform agnostic
mpi-op                         MPI-Operator
pytorch-op                     Pytorch op
tekton                         Kubeflow Pipelines based on Tekton
tensorflow-op                  Kubeflow Tensorflow
```
also from third time the cache works great in terms of performance.
One thing I've noticed is that it create 2 folders under the .k3ai one:
```BASH
    Directory: C:\Users\AlessandroFesta\.k3ai\cache


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        19/11/2020     08:51                kf5i
d-----        19/11/2020     08:51                repos
```
that got more or less the same content.

**Comment by Gsantomaggio** [comment]
The plugin cache seems to work correctly, but I think it requires more job.
At the moment the cache downloads the repo in this way:
```
{
      "name":"h2o-single",
      "path":"core/plugins/h2o-single",
      "sha":"63a98ec370005c302b031181f73161968d9032a4",
      "size":0,
      "url":"https://api.github.com/repos/kf5i/k3ai-plugins/contents/core/plugins/h2o-single?ref=main",
      "html_url":"https://github.com/kf5i/k3ai-plugins/tree/main/core/plugins/h2o-single",
      "git_url":"https://api.github.com/repos/kf5i/k3ai-plugins/git/trees/63a98ec370005c302b031181f73161968d9032a4",
      "download_url":null,
      "type":"dir",
      "_links":{
         "self":"https://api.github.com/repos/kf5i/k3ai-plugins/contents/core/plugins/h2o-single?ref=main",
         "git":"https://api.github.com/repos/kf5i/k3ai-plugins/git/trees/63a98ec370005c302b031181f73161968d9032a4",
         "html":"https://github.com/kf5i/k3ai-plugins/tree/main/core/plugins/h2o-single"
      }
```

so the `err := ps.Encode(shared.NormalizeURL(URL, gHubContent.Name) + DefaultPluginFileName)` has to access on github to decode the data. 

The idea is to have a full dump locally so the user won't access on the remote repository anymore. 

We were thinking to add one command on the "list" like "update" to download explicitly the new plugins, like:

```
k3ai-list list update
```

**Review by Gsantomaggio — CHANGES_REQUESTED** [review]
https://github.com/kf5i/k3ai-core/pull/67#issuecomment-735245292

**Pull request closed without merging**
